language: node_js
sudo: false
node_js:
    - 0.10
install:
    - npm install
    - export PATH="node_modules/.bin:$PATH"
    - psc --version
    - pulp --version
    - pulp dep update
script:
    - pulp build
    - pulp test
